### ISSUE TITLE
Incorrect begin-end date/time in plot X-axis

### ISSUE THREAD

**Issue by justb4** [ruben-mv/SOSClient#7]
When trying to visualize a plot from a GetObservation result the date-time boxes show incorrect times (somewhere around 1936) 

![time2](https://cloud.githubusercontent.com/assets/582630/9718478/5b11af58-557c-11e5-8410-a0c370d83c11.png)

The GetObservation response seems correct and with the following format as in image

![time](https://cloud.githubusercontent.com/assets/582630/9718440/faecaee8-557b-11e5-9d81-1969fef543e7.png)

Not clear why this happens, possibly a problem in date/time parsing?

**Comment by ruben-mv** [comment]
Will be fixed on next release.
