### ISSUE TITLE
Error loading various SOS resources

### ISSUE THREAD

**Issue by lmenard** [ruben-mv/SOSClient#8]
Hi,
I've downloaded and installed the SOS plugin for QGIS (V2.12.0 Lyon on a Mac) and I've tried 3 different SOS resources GetCapabilities. Though each of them bring me back the information and the structure of the SOS, I'm not able to load the FOI (Features Of Interest) neither am I able to print a graph as presented in the Help document attached with the plugin.

Here is one resource I tried:
http://www.pegelonline.wsv.de/webservices/gis/sos?request=GetCapabilities&service=SOS&VERSION=1.0.0

I get various errors:
"unexpected character in line 1, column 50": when I try to add element of the resources 
and the following one when trying to load the XML:
TypeError: object of type 'NoneType' has no len() 
Traceback (most recent call last):
  File "/Users/lionelmenard/.qgis2/python/plugins/SOSClient/sos_client.py", line 223, in showLayerXml
    if len (xml):
TypeError: object of type 'NoneType' has no len())

Could someone test the resource above and make it print the FOI and graph ?
What would you need from my side to help resolving the problem.

Thanks again for this valuable effort to provide access to SOS in QGIS !

Lionel

**Comment by ruben-mv** [comment]
Hi Lionel,

when execute GetObservations request to http://pegelonline.wsv.de/webservices/gis/gdi-sos , server return an html with 320 status code instead of an xml observation collection.

**Comment by lmenard** [comment]
Hi, thanks for your response. I'm not sure what is a 320 status code or is it a 302 one meaning that you can have GetCapabilities properly responding and not GetObservation operation on this ressource ?
As I said I've tested other servers. This one has, like the other one, a working GetCapabilities:
http://insitu.webservice-energy.org/52n-sos-webapp/sos?service=SOS&REQUEST=GetCapabilities
and also a working GetObservation:
http://insitu.webservice-energy.org/52n-sos-webapp/sos?service=SOS&request=GetObservation&version=2.0.0&procedure=KZ-CH1&featureOfInterest=ENTPE&temporalFilter=om%3AphenomenonTime%2C2014-12-30T23%3A00%3A00Z%2F2014-12-31T23%3A00%3A00Z&

Are you able to run it under QGIS using the plugin ?

Could you also provide a link to a GetCapabilities resource that works using the plugin ?

Thanks once again for your support.

Cheers,

Lionel
